using System.Collections.Generic;

namespace VSAgent.Services.I18n
{
    /// <summary>
    /// Translation tables for the workbench UI. Keys are stable identifiers
    /// (kebab/snake-style) so they stay readable across languages and survive
    /// string re-ordering in either culture.
    ///
    /// Adding a string:
    ///   1. Add a key to every dictionary in <see cref="Tables"/>.
    ///   2. Reference it via <c>LocalizationService.Current["key"]</c> or
    ///      <c>LocalizedStrings.Lookup("key")</c>.
    /// </summary>
    public static class LocalizedStrings
    {
        public static readonly Dictionary<string, Dictionary<string, string>> Tables = new()
        {
            ["en-US"] = new()
            {
                ["app.title"] = "Quantivus OMP",
                ["app.subtitle"] = "Session restored. Analyse the project",
                ["tab.chat"] = "Chat",
                ["tab.chat.subtitle"] = "Conversation and live tools",
                ["tab.tasks"] = "Tasks",
                ["tab.tasks.subtitle"] = "Runs and follow-up queue",
                ["tab.agents"] = "Agents",
                ["tab.agents.subtitle"] = "Focused agent profiles",
                ["tab.repository"] = "Repository",
                ["tab.repository.subtitle"] = "Solution and project overview",
                ["tab.changes"] = "Changes",
                ["tab.changes.subtitle"] = "Git diff and commits",
                ["tab.terminal"] = "Terminal",
                ["tab.terminal.subtitle"] = "Cancellable shell commands",
                ["tab.context"] = "Context",
                ["tab.context.subtitle"] = "Inspectable prompt context",
                ["tab.prompts"] = "Prompts",
                ["tab.prompts.subtitle"] = "Reusable prompt library",
                ["tab.sessions"] = "Sessions",
                ["tab.sessions.subtitle"] = "Restore and export sessions",
                ["tab.skills"] = "Skills",
                ["tab.skills.subtitle"] = "OMP skills",
                ["tab.tools"] = "Tools",
                ["tab.tools.subtitle"] = "Custom MCP tools",
                ["tab.dllspy"] = "DLLSpy",
                ["tab.dllspy.subtitle"] = "Inspect DLLs, types and dependencies",
                ["tab.diagnostics"] = "Diagnostics",
                ["tab.diagnostics.subtitle"] = "Runtime and installation checks",
                ["settings.language"] = "Language",
                ["settings.provider"] = "Provider",
                ["settings.model"] = "Model",
                ["settings.search"] = "Web search",
                ["settings.advanced"] = "Advanced",
                ["settings.title"] = "Provider and extension settings",
                ["chat.placeholder"] = "Describe the task... (Ctrl+Enter to send, type / for commands, Esc to cancel). Drop images or files here — paste with Ctrl+V.",
                ["chat.send"] = "Send",
                ["chat.cancel"] = "Cancel",
                ["chat.clear"] = "Clear",
                ["chat.copy"] = "Copy",
                ["chat.export"] = "Export",
                ["chat.drop.hint"] = "Ctrl+Enter sends • / opens commands • Esc cancels • files can be dropped here",
                ["chat.idle"] = "Idle",
                ["chat.busy"] = "oh-my-pi is working...",
                ["chat.cancelled"] = "Cancelled",
                ["chat.error"] = "Error",
                ["chat.context.controlled"] = "Inspectable context is controlled in Context",
                ["welcome.hint"] = "Type a prompt and press Ctrl+Enter to send.  Esc cancels.  / for commands.",
                ["welcome.tagline"] = "\u03C0  +  Quantivus for Visual Studio",
                ["welcome.initializing"] = "Initializing oh-my-pi...",
                ["dllspy.open"] = "Open assembly...",
                ["dllspy.recent"] = "Recent",
                ["dllspy.analyze"] = "Analyse",
                ["dllspy.refresh"] = "Refresh",
                ["dllspy.types"] = "Types",
                ["dllspy.members"] = "Members",
                ["dllspy.details"] = "Details",
                ["dllspy.dependencies"] = "Dependencies",
                ["dllspy.graph"] = "Dependency graph",
                ["dllspy.empty"] = "Open a .dll or .exe to inspect its types, members and dependencies.",
                ["dllspy.managed"] = "Managed (.NET) assembly",
                ["dllspy.unmanaged"] = "Unmanaged (native) module",
                ["dllspy.invalid"] = "Not a valid PE file",
                ["dllspy.no.exports"] = "No exports found.",
                ["dllspy.exports"] = "Exports",
                ["dllspy.kind.class"] = "Class",
                ["dllspy.kind.interface"] = "Interface",
                ["dllspy.kind.struct"] = "Struct",
                ["dllspy.kind.enum"] = "Enum",
                ["dllspy.kind.delegate"] = "Delegate",
                ["dllspy.kind.method"] = "Method",
                ["dllspy.kind.property"] = "Property",
                ["dllspy.kind.field"] = "Field",
                ["dllspy.kind.event"] = "Event",
                ["dllspy.kind.constructor"] = "Constructor",
                ["dllspy.summary"] = "{0} types, {1} references",
                ["dllspy.node.central"] = "Selected",
                ["dllspy.node.reference"] = "References",
                ["dllspy.node.referencedBy"] = "Referenced by",
                ["dllspy.zoom.in"] = "Zoom in",
                ["dllspy.zoom.out"] = "Zoom out",
                ["dllspy.zoom.fit"] = "Fit",
                ["dllspy.layout"] = "Re-layout",
                ["dllspy.search"] = "Search types...",
                ["toolbar.new"] = "New",
                ["toolbar.restart"] = "Restart",
                ["toolbar.stop"] = "Stop",
                ["statusbar.idle"] = "Idle",
                ["provider.default"] = "Default provider",
                ["common.cancel"] = "Cancel",
                ["common.apply"] = "Apply",
                ["common.save"] = "Save",
                ["common.delete"] = "Delete",
                ["common.refresh"] = "Refresh",
                ["common.browse"] = "Browse...",
                ["common.none"] = "(none)",
            },
            ["de-DE"] = new()
            {
                ["app.title"] = "Quantivus OMP",
                ["app.subtitle"] = "Sitzung wiederhergestellt. Projekt wird analysiert",
                ["tab.chat"] = "Chat",
                ["tab.chat.subtitle"] = "Konversation und Live-Tools",
                ["tab.tasks"] = "Aufgaben",
                ["tab.tasks.subtitle"] = "Läufe und Folgeaufträge",
                ["tab.agents"] = "Agenten",
                ["tab.agents.subtitle"] = "Fokussierte Agent-Profile",
                ["tab.repository"] = "Repository",
                ["tab.repository.subtitle"] = "Lösung und Projektübersicht",
                ["tab.changes"] = "Änderungen",
                ["tab.changes.subtitle"] = "Git-Diff und Commits",
                ["tab.terminal"] = "Terminal",
                ["tab.terminal.subtitle"] = "Abbrechbare Shell-Befehle",
                ["tab.context"] = "Kontext",
                ["tab.context.subtitle"] = "Inspizierbarer Prompt-Kontext",
                ["tab.prompts"] = "Prompts",
                ["tab.prompts.subtitle"] = "Wiederverwendbare Prompt-Bibliothek",
                ["tab.sessions"] = "Sitzungen",
                ["tab.sessions.subtitle"] = "Sitzungen wiederherstellen und exportieren",
                ["tab.skills"] = "Skills",
                ["tab.skills.subtitle"] = "OMP-Skills",
                ["tab.tools"] = "Tools",
                ["tab.tools.subtitle"] = "Eigene MCP-Tools",
                ["tab.dllspy"] = "DLLSpy",
                ["tab.dllspy.subtitle"] = "DLLs, Typen und Abhängigkeiten untersuchen",
                ["tab.diagnostics"] = "Diagnose",
                ["tab.diagnostics.subtitle"] = "Laufzeit- und Installationsprüfungen",
                ["settings.language"] = "Sprache",
                ["settings.provider"] = "Anbieter",
                ["settings.model"] = "Modell",
                ["settings.search"] = "Websuche",
                ["settings.advanced"] = "Erweitert",
                ["settings.title"] = "Anbieter- und Erweiterungseinstellungen",
                ["chat.placeholder"] = "Aufgabe beschreiben... (Strg+Enter zum Senden, / für Befehle, Esc zum Abbrechen). Bilder oder Dateien hier ablegen — mit Strg+V einfügen.",
                ["chat.send"] = "Senden",
                ["chat.cancel"] = "Abbrechen",
                ["chat.clear"] = "Leeren",
                ["chat.copy"] = "Kopieren",
                ["chat.export"] = "Exportieren",
                ["chat.drop.hint"] = "Strg+Enter sendet • / öffnet Befehle • Esc bricht ab • Dateien können abgelegt werden",
                ["chat.idle"] = "Bereit",
                ["chat.busy"] = "oh-my-pi arbeitet...",
                ["chat.cancelled"] = "Abgebrochen",
                ["chat.error"] = "Fehler",
                ["chat.context.controlled"] = "Inspizierbarer Kontext wird in Kontext verwaltet",
                ["welcome.hint"] = "Prompt eingeben und Strg+Enter zum Senden drücken.  Esc bricht ab.  / für Befehle.",
                ["welcome.tagline"] = "\u03C0  +  Quantivus für Visual Studio",
                ["welcome.initializing"] = "oh-my-pi wird initialisiert...",
                ["dllspy.open"] = "Assembly öffnen...",
                ["dllspy.recent"] = "Zuletzt verwendet",
                ["dllspy.analyze"] = "Analysieren",
                ["dllspy.refresh"] = "Aktualisieren",
                ["dllspy.types"] = "Typen",
                ["dllspy.members"] = "Member",
                ["dllspy.details"] = "Details",
                ["dllspy.dependencies"] = "Abhängigkeiten",
                ["dllspy.graph"] = "Abhängigkeitsgraph",
                ["dllspy.empty"] = ".dll oder .exe öffnen, um Typen, Member und Abhängigkeiten zu untersuchen.",
                ["dllspy.managed"] = "Verwaltete (.NET) Assembly",
                ["dllspy.unmanaged"] = "Unverwaltetes (natives) Modul",
                ["dllspy.invalid"] = "Keine gültige PE-Datei",
                ["dllspy.no.exports"] = "Keine Exporte gefunden.",
                ["dllspy.exports"] = "Exporte",
                ["dllspy.kind.class"] = "Klasse",
                ["dllspy.kind.interface"] = "Schnittstelle",
                ["dllspy.kind.struct"] = "Struktur",
                ["dllspy.kind.enum"] = "Enumeration",
                ["dllspy.kind.delegate"] = "Delegat",
                ["dllspy.kind.method"] = "Methode",
                ["dllspy.kind.property"] = "Eigenschaft",
                ["dllspy.kind.field"] = "Feld",
                ["dllspy.kind.event"] = "Ereignis",
                ["dllspy.kind.constructor"] = "Konstruktor",
                ["dllspy.summary"] = "{0} Typen, {1} Verweise",
                ["dllspy.node.central"] = "Ausgewählt",
                ["dllspy.node.reference"] = "Verweise auf",
                ["dllspy.node.referencedBy"] = "Verwiesen von",
                ["dllspy.zoom.in"] = "Vergrößern",
                ["dllspy.zoom.out"] = "Verkleinern",
                ["dllspy.zoom.fit"] = "Anpassen",
                ["dllspy.layout"] = "Neu anordnen",
                ["dllspy.search"] = "Typen suchen...",
                ["toolbar.new"] = "Neu",
                ["toolbar.restart"] = "Neustart",
                ["toolbar.stop"] = "Stopp",
                ["statusbar.idle"] = "Bereit",
                ["provider.default"] = "Standardanbieter",
                ["common.cancel"] = "Abbrechen",
                ["common.apply"] = "Übernehmen",
                ["common.save"] = "Speichern",
                ["common.delete"] = "Löschen",
                ["common.refresh"] = "Aktualisieren",
                ["common.browse"] = "Durchsuchen...",
                ["common.none"] = "(keine)",
            }
        };
    }
}
